url: "https://dattaadvocate.com"
baseurl: ""

# Site settings
title: Datta Advocate
email: me@dattaadvocate.com
description: "Trauma-informed education and housing advocacy for families"


# Team names, titles and social links
people:
- name: Neera Datta
  pic: 1
  position: Lead Advocate
  social:
    - title: pinterest
      url: "https://www.pinterest.com/dattaadvocates/"
    - title: facebook
      url: "https://www.instagram.com/dattaadvocate/"
    - title: instagram
      url: "https://www.instagram.com/dattaadvocate/"
    - title: bluesky
      url: "https://bsky.app/profile/dattaadvocate.bsky.social"

- name: Neera Datta
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: instagram
      url: "https://www.instagram.com/dattaadvocate/"

- name: Gunjan Datta
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: instagram
      url: 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url:
  - title: pinterest
    url: 
  - title: instagram
    url: "https://www.instagram.com/dattaadvocate/"
  - title: bluesky
    url: "https://bsky.app/profile/dattaadvocate.bsky.social"

# Postal address (add as many lines as necessary)
address:
  - line: 123 Main St.
  - line: Oakton, VA 22124

# Build settings
markdown: kramdown
permalink: pretty